name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Check pre-commit status
        run: |
          if [ $? -ne 0 ]; then
            echo "Pre-commit checks failed. Please fix the issues and try again."
            exit 1
          fi
